### PR TITLE
feat: add parameters prop

### PR DESCRIPTION
**Pull request by franciscorode**
`parameters` prop added to give more options without overload component properties

### CODE REVIEW

**Comment by andrewvasilchuk** [comment]
@franciscorode, Thanks for the PR. I will review it today.

**Comment by andrewvasilchuk** [comment]
@franciscorode, Please review the changes. If we are good with them, I'm ready to merge into the `dev` branch.

**Comment by andrewvasilchuk** [comment]
@franciscorode, Should I release a new version? Is it urgent to you?

**Comment by franciscorode** [comment]
> @franciscorode, Please review the changes. If we are good with them, I'm ready to merge into the `dev` branch.

All changes seem me fine, good work! Only a detail about the readme, the link to `parameters` prop in the description of `enablejsapi` and `autoplay` props don't redirect well to the new parameter

**Comment by franciscorode** [comment]
> @franciscorode, Should I release a new version? Is it urgent to you?

Yes it is not very urgent but it would be great

**Comment by franciscorode** [comment]
> > @franciscorode, Please review the changes. If we are good with them, I'm ready to merge into the `dev` branch.
> 
> All changes seem me fine, good work! Only a detail about the readme, the link to `parameters` prop in the description of `enablejsapi` and `autoplay` props don't redirect well to the new parameter

@andrewvasilchuk I have done the change to do it linkable, I see it well like that but if you prefer we can remove it and remove the link to `parameters` prop in the description of `enablejsapi` and `autoplay` props

**Comment by andrewvasilchuk** [comment]
@franciscorode, I've removed deprecation messages by now. Moreover, `autoplay` prop is not related to the `autoplay` parameter. Thank you so much for this PR. Merging into the `dev` branch.

**Comment by andrewvasilchuk** [comment]
@franciscorode, `2.3.0` version is published 🎉

**Comment by franciscorode** [comment]
> @franciscorode, `2.3.0` version is published 🎉

Great!

**Pull request merged**
