### PR TITLE
feat: add property to disable related videos

### PR DESCRIPTION
**Pull request by franciscorode**
First, congrats by the repo!
I tried to disable related videos by adding `rel` option in `playerOptions` with `playerVars` but for some reason, it didn't work, the only way to make it work was to add it as a GET parameter in the `src` prop. To not set options in several sites I think is better to add it as a prop and I have added the changes to do it

### CODE REVIEW

**Comment by andrewvasilchuk** [comment]
@franciscorode, Thanks for the PR. You can pass `src` prop as `'https://www.youtube.com/embed/$ID?rel=0'`. I've just checked it out and it works.

**Note**: that you can't disable related videos referring to the [docs](https://developers.google.com/youtube/player_parameters#rel).

> After the change, you will not be able to disable related videos. Instead, if the `rel` parameter is set to `0`, related videos will come from the same channel as the video that was just played.

**Comment by andrewvasilchuk** [comment]
I don't think it's a good idea to introduce a separate prop for every [parameter](https://developers.google.com/youtube/player_parameters#Parameters), since it will make component really large. Moreover you can pass any of them via `src` prop.

`autoplay` and `enablejsapi` props were introduce since they **change** the way how component behaves.

**Comment by franciscorode** [comment]
I understand your position, it's fine although I don't like the idea of ​​passing options in the URL. I tried to pass the option in prop `playerOptions` but I could not know why it did not work for me, other options work well such as events. 
If you find of good way to pass options outside of the URL and without overloading the properties component let me know I'll be happy to help

**Comment by andrewvasilchuk** [comment]
@franciscorode, We can add `parameters` prop, which can include all the [parameters](https://developers.google.com/youtube/player_parameters#Parameters).  All we need to do is correctly construct the URL.

**Comment by franciscorode** [comment]
Yes seem a good idea, I understand these points, tell me if you don't agree with some of them
- The prop will be type `Object` with a default empty object
- The description of the API documentation for the prop will show a link to the official [parameters](https://developers.google.com/youtube/player_parameters#Parameters) doc
- The possible name and values ​​of options will base on youtube API
- Will be the responsibility of the developer set correctly the option names and values in a similar way to `playerOptions` prop
- The computed property `srcAttribute` will add each option to the URL
- The `enablejsapi` and `autoplay` props should be passed only in this prop instead have own props, to don't break retrocompatibility will maintain them but we should add a warning about your deprecation with the objective of remove them in a future

**Comment by andrewvasilchuk** [comment]
@franciscorode, awesome!

**Comment by franciscorode** [comment]
Good! I can work on this, give me a few days and create another pull request, close this

**Comment by andrewvasilchuk** [comment]
@franciscorode, Thank you so much. I will be glad to review your PR.

**Pull request closed without merging**
