### PR TITLE
Youtube Short URL / List URL support

### PR DESCRIPTION
**Pull request by parsher**
Hello. Thank you for creating this component.
I added some features. Would you merge this?
If you don't like my code styles, please modify anything that you want.

**Added features**:
* Youtube Short URL support / List URL support

**History**:
* `URL` validation added
* `URL` regex added
* `generateURL` modified
* data `id` added
* data `urlQuery` added
* `setUrlInformation` created

### CODE REVIEW

**Comment by andrewvasilchuk** [comment]
@parsher, Thank you for your PR. Maybe we should be more declarative? I do not think it's good idea to introduce `watch` and `method` instead of `computed`. To support short URL we should change the `regExp` a bit. I would like to merge you PR, with the new `regExp` :)

Or should I do it itself?

**Comment by sbagdaulet** [comment]
/(?:(?:v=|(?:v%3D))|(?:\/(?:v|e)\/)|(?:(?:(?:youtu\.be)|(?:embed))\/))([^&\n#?%]+)/

try this

**Comment by andrewvasilchuk** [comment]
Why do we need the `urlQuery` computed property? There is already a `query` prop you can pass along.

**Comment by andrewvasilchuk** [comment]
The [list](https://gist.github.com/rodrigoborgesdeoliveira/987683cfbfcc8d800192da1e73adc486) of all URL formats of YouTube.

**Comment by andrewvasilchuk** [comment]
ASAP I have free time I am going to support 90% of the available YouTube URL`s. Also I'am going to introduce a `videoId` prop.

**Comment by parsher** [comment]
@andrewvasilchuk Yes, we don't need the urlQuery, if we supply the query prop manually. I just want that this component can handle the all possible query parameters automatically, even if I didn't pass that ones. If you have a time for handling this, I think that I should close this PR. Thanks for checking this!

**Comment by andrewvasilchuk** [comment]
Closed via c22b45583502852dd7deca693691d4042f79f3fa. It's only supported in `1.x`.

**Pull request closed without merging**
