### PR TITLE
feat: add thumbnailListeners prop

### PR DESCRIPTION
**Pull request by grelkin**
Bubble the `load` event up.

### CODE REVIEW

**Comment by andrewvasilchuk** [comment]
@grelkin, Let's create `imgListeners` prop. So we can listen to all the events not to the `load`. What do you think about it?)

**Comment by andrewvasilchuk** [comment]
@grelkin, What do you think about it? Ready to merge 😄

**Comment by grelkin** [comment]
Yup, it's definitely more advanced and covers my case.

Thanks a lot.

**Comment by grelkin** [comment]
@andrewvasilchuk, Thank you very much for reviewing and accepting the PR so fast.

Would you also have an opportunity to update the NPM package with the changes in the next few weeks ?

**Comment by andrewvasilchuk** [comment]
@grelkin, Sure, tomorrow, I promise.

**Comment by andrewvasilchuk** [comment]
@grelkin, Publised.

**Pull request merged**
